

Vagrant::Config.run do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.forward_port 8893, 8893
  config.vm.forward_port 8080, 8080
  config.vm.network :hostonly, "192.168.1.50"
  
  config.vm.share_folder "v-data", "/opt/data", "../data"
  config.vm.provision :chef_solo do |chef|
    
  chef.add_recipe "tomcat-solr"


  end
end